import type { Database, TablesInsert, TablesUpdate } from '~/types/database.types'

type PublicTable = keyof Database['public']['Tables']

type TableField<T extends PublicTable> = Extract<
  keyof TablesInsert<T> | keyof TablesUpdate<T>,
  string
>

export const TABLE_FIELDS = {
  "artisan_colorways": [
    "colorway_id",
    "created_at",
    "currency",
    "deleted",
    "description",
    "fts",
    "id",
    "img",
    "maker_id",
    "maker_sculpt_id",
    "name",
    "order",
    "overridden_fields",
    "photo_credit",
    "price",
    "qty",
    "release",
    "review_note",
    "review_status",
    "sale_type",
    "sculpt_id",
    "source",
    "source_document_id",
    "stem",
    "submitted_by",
    "verified_at",
    "verified_by"
  ],
  "artisan_makers": [
    "artisancollector",
    "bio",
    "contributors",
    "country_origin",
    "deleted",
    "disable_google_sync",
    "discord",
    "document_ids",
    "founded",
    "fts",
    "id",
    "instagram",
    "invertible_logo",
    "name",
    "updated_at",
    "verified",
    "website"
  ],
  "artisan_sculpts": [
    "cast",
    "collection",
    "created_at",
    "deleted",
    "design",
    "fts",
    "id",
    "img",
    "is_revision_of",
    "maker_id",
    "maker_sculpt_id",
    "name",
    "overridden_fields",
    "profile",
    "release",
    "review_status",
    "sculpt_id",
    "source",
    "source_document_id",
    "story",
    "submitted_by",
    "verified_at",
    "verified_by"
  ],
  "colors": [
    "code",
    "created_at",
    "fts",
    "hex",
    "id",
    "name",
    "system"
  ],
  "feedbacks": [
    "created_at",
    "email",
    "id",
    "message",
    "name",
    "resolved"
  ],
  "keyboard_brands": [
    "bio",
    "country_origin",
    "created_at",
    "discord",
    "fts",
    "id",
    "instagram",
    "invertible_logo",
    "name",
    "slug",
    "website"
  ],
  "keyboard_releases": [
    "brand_keyboard_slug",
    "brand_slug",
    "case_materials",
    "created_at",
    "currency",
    "description",
    "fts",
    "id",
    "msrp_price",
    "name",
    "order",
    "pcb_types",
    "plate_materials",
    "release_year",
    "review_status",
    "submitted_by",
    "variant_specs",
    "verified_at",
    "verified_by",
    "weight_materials"
  ],
  "keyboard_variants": [
    "brand_keyboard_slug",
    "brand_slug",
    "case_materials",
    "created_at",
    "currency",
    "finish_type",
    "fts",
    "id",
    "img_back",
    "img_front",
    "msrp_price",
    "pcb_types",
    "photo_credit",
    "plate_materials",
    "release_id",
    "release_year",
    "review_note",
    "review_status",
    "sale_type",
    "submitted_by",
    "units_produced",
    "variant_name",
    "verified_at",
    "verified_by",
    "weight_materials"
  ],
  "keyboards": [
    "brand_keyboard_slug",
    "brand_slug",
    "created_at",
    "derived_from",
    "description",
    "form_factor",
    "fts",
    "id",
    "mount_styles",
    "name",
    "review_status",
    "slug",
    "submitted_by",
    "top_case_styles",
    "typing_angle",
    "verified_at",
    "verified_by"
  ],
  "keyset_colors": [
    "color_id",
    "created_at",
    "id",
    "profile_keyset_id"
  ],
  "keyset_kits": [
    "cancelled",
    "created_at",
    "description",
    "id",
    "img",
    "kit_id",
    "name",
    "price",
    "profile_keyset_id",
    "qty",
    "review_note",
    "review_status",
    "submitted_by",
    "verified_at",
    "verified_by"
  ],
  "keyset_profiles": [
    "description",
    "id",
    "manufacturer",
    "manufacturer_id",
    "name",
    "profile"
  ],
  "keysets": [
    "created_at",
    "description",
    "designer",
    "end_date",
    "fts",
    "ic_date",
    "id",
    "img",
    "name",
    "order_graph",
    "order_history",
    "profile_id",
    "profile_keyset_id",
    "review_status",
    "sculpt",
    "start_date",
    "status",
    "submitted_by",
    "url",
    "verified_at",
    "verified_by"
  ],
  "kit_categories": [
    "description",
    "id",
    "name",
    "slug",
    "sort_order"
  ],
  "notification_preferences": [
    "enabled",
    "preference",
    "updated_at",
    "user_id"
  ],
  "notifications": [
    "actor_id",
    "created_at",
    "data",
    "entity_id",
    "entity_type",
    "id",
    "read_at",
    "type",
    "user_id"
  ],
  "testimonials": [
    "avatar_url",
    "content",
    "created_at",
    "featured",
    "id",
    "name",
    "role",
    "status"
  ],
  "user_collection_items": [
    "artisan_item_id",
    "asking_price",
    "collection_id",
    "exchange",
    "id",
    "keyboard_item_id",
    "keyset_item_id",
    "order",
    "priority",
    "uid"
  ],
  "user_collections": [
    "category",
    "contact",
    "created_at",
    "id",
    "intent",
    "message",
    "name",
    "published",
    "sort_by",
    "uid"
  ],
  "users": [
    "appearance",
    "assignments",
    "discord",
    "email",
    "favorite_makers",
    "full_name",
    "id",
    "qq",
    "reddit",
    "role"
  ]
} satisfies {
  [K in PublicTable]: readonly TableField<K>[]
}
